image_width: 640
image_height: 480
camera_name: zed_camera/left
camera_matrix:
  rows: 3
  cols: 3
  data: [504.78216005824515, 0., 320.5, 0., 504.78216005824515, 240.5, 0., 0., 1.]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0., 0., 0., 0., 0.]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0., 0., 1., 0., 0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [4827.94, 0., 1223.5, 0., 0., 4835.62, 1024.5, 0., 0., 0., 1., 0.]


#   header:
#   stamp:
#     sec: 6487
#     nanosec: 587000000
#   frame_id: base_link
# height: 480
# width: 640
# distortion_model: plumb_bob
# d:
# - 0.0
# - 0.0
# - 0.0
# - 0.0
# - 0.0
# k:
# - 504.78216005824515
# - 0.0
# - 320.5
# - 0.0
# - 504.78216005824515
# - 240.5
# - 0.0
# - 0.0
# - 1.0
# r:
# - 1.0
# - 0.0
# - 0.0
# - 0.0
# - 1.0
# - 0.0
# - 0.0
# - 0.0
# - 1.0
# p:
# - 504.78216005824515
# - 0.0
# - 320.5
# - -60.57385920698942
# - 0.0
# - 504.78216005824515
# - 240.5
# - 0.0
# - 0.0
# - 0.0
# - 1.0
# - 0.0
# binning_x: 0
# binning_y: 0
# roi:
#   x_offset: 0
#   y_offset: 0
#   height: 0
#   width: 0
#   do_rectify: false
